100-hours-a-week/7-team-kono-fe

src/api/user.ts
src/config/apiEndpoints.ts
src/contexts/AuthContext.tsx
src/pages/Settings.tsx

1. 🛠️ 프로필 변경 API 백 프론트 연동
2. 📝 회원탈퇴 API 백 프론트 연동
3. 🔧 회원 로그아웃 백 프론트 연동
1. ✅ 회원 탈퇴 후 로그인 테스트 성공
2. 🖥️ 프로필 변경 후 S3. 이미지 업로드 및 db 변경 확인 
3. 📱 닉네임 변경 후 db 변경 및 확인
- [] ✅ 모든 테스트가 성공적으로 통과했습니다.

feature:프로필,회원탈퇴,로그아웃 연결

---

src/pages/Transaction.tsx

fix/transaction-get-date -> develop
매매내역 : "날짜 없음"으로 떴던 이슈 수정함.
- Resolves #67 
1. 🛠️ [변경 내용 1] creatAt 변수명을 createdAt으로 수정함
2. 📝 [변경 내용 2]
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]

fix: 매매내역 페이지 날짜 불러오기

---

src/api/transaction.ts

chore/createdAt → develop
날짜 엔티티 이름 수정
createdAt에 d 추가

chore: fix createdAt + d

---

src/pages/Wallet.tsx

develop -->feature/calculateTotalProfitRate
전체 수익금 수익률 로직 변경

fix: calculateTotalProfitRate 로직 변경

---

src/pages/Trade.tsx

feature/validator → develop
유효성 검사 추가
- Resolves #[이슈 번호]
1. 🛠️ [변경 내용 1]
2. 📝 [변경 내용 2]
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]

fix: add validator on trade page

---

src/components/layout/Header.tsx
src/pages/Trade.tsx

develop
매매페이지에서 뒤로가기 버튼 2개 중복된거 삭제 
- Resolves #122 
1. 🛠️ [변경 내용 1] 헤더 수정
2. 📝 [변경 내용 2] 매매페이지 헤더 수정
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]

fix: remove duplicate back buttons

---

src/api/ranking.ts
src/pages/Ranking.tsx
src/pages/Trade.tsx

feat/fix-ranking-updated-at -> develop 
- Resolves #109 
1. 🛠️ [변경 내용 1] 랭킹 시간 : 백엔드에서 응답받은 시간으로 수정함 
2. 📝 [변경 내용 2]
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]
- [] 👀 코드 리뷰어를 지정했습니다.

feat: fix ranking updated at

---

src/pages/CoinDetail.tsx
src/pages/Trade.tsx

feature/validator → develop
해당 코인을 보유하지 않은 경우 코인 상세 페이지 이동시 판매 버튼을 보이지 않게 숨겼습니다.
- Resolves #121

fix(ui): hide sell button when user has no coin holdings  @hyogshin

---

src/main.tsx

sentry 모니터링 추가
1. 🛠️ [변경 내용 1]
2. 📝 [변경 내용 2]
3. 🔧 [변경 내용 3]
실행 예시
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]

feat: add sentry

---

src/pages/Wallet.tsx

feature/total_profitrate -> develop
수익률 변화
예시)
* 현재 시세: 8,000원
* 평균 단가: 9,000원
* 손실률 = (8,000 - 9,000) / 9,000 = -11.11%
적용이 안되고 소량 판매시에도 0%부터 다시 시작하는 오류 수정
- Resolves #144

feat: fix total profit rate

---

src/pages/Profile.tsx

fix: 닉네임 업로드 수정

---

src/pages/Ranking.tsx

- 랭킹페이지 최적화를 위해 이미지를 스크롤한 시점에 불러오도록 변경
- Resolves #[이슈 번호]
1. 🛠️ [변경 내용 1] 랭킹 최적화
2. 📝 [변경 내용 2] 삭제된 ranking부분 되돌려놓음
3. 🔧 [변경 내용 3]

feat: optimize ranking page images

---

src/components/layout/BottomNavigation.tsx

feat/nav-bar-add-text -> main
네비게이션바 아래 설명 텍스트 추가
- Resolves #89

feat: 네비게이션바 설명 텍스트 추가

---

package.json

fix:homepage-uri-accept

---

src/api/clients.ts
src/pages/Discover.tsx
src/pages/Favorite.tsx
src/pages/Ranking.tsx
src/pages/Settings.tsx
src/pages/Transaction.tsx
src/pages/Wallet.tsx

feat: add buy me a beer

---

src/components/theme/DarkModeToggle.tsx
src/pages/Settings.tsx
src/pages/Wallet.tsx
tailwind.config.js

feature/style -> main
- mono 폰트 패밀리 적용
- bottom navbar 스타일링
- 다크모드 해/달 토글

design: add icon to dark mode toggle

---

index.html
src/assets/kono_icon.svg

feat/change-tab-icon -> main
브라우저탭에 보이는 아이콘 변경 (노란색코인아이콘으로)

refactor: change tab icon

---

.gitignore
index.html
src/contexts/AuthContext.tsx
src/main.tsx
src/pages/CoinDetail.tsx

feature/google-analytics → develop

feat: google Analytics

---

src/api/clients.ts
src/contexts/AuthContext.tsx
src/pages/CoinDetail.tsx

fix: login

---

src/components/layout/BottomNavigation.tsx

design: set navbar active

---

src/components/layout/BottomNavigation.tsx

fix: ts error

---

index.html
src/components/layout/BottomNavigation.tsx
src/components/layout/Layout.tsx
src/pages/Ranking.tsx

hotfix/style -> main
작은 폰에서 레이아웃이 커지는 오류 수정

chore: fix layout
